const constants = {
    DELETE_BOOK:'DELETE_BOOK',
    SAVE_BOOK:'SAVE_BOOK',
    ADD_BOOK:'ADD_BOOK',
    DELETE_AUTHOR: 'DELETE_AUTHOR',
    SAVE_AUTHOR:'SAVE_AUTHOR',
    ADD_AUTHOR:'ADD_AUTHOR',
    ADD_EX_DATA:'ADD_EX_DATA'
}

export default constants